In [1]:
import pandas as pd
import numpy as np

In [ ]:
deepcsa_output_dir = "/home/fcalvet/Downloads/to_remove/normal_bladder_urothelium/bladder_paper_data/deepCSA_outputs"
average_depths_per_sample_file = f"{deepcsa_output_dir}/depthssummary/all_samples.exons_cons.avgdepth_per_sample.tsv"

all_mutations_file = f"{deepcsa_output_dir}/clean_somatic/all_samples.somatic.mutations.tsv"
all_depths_file = f"{deepcsa_output_dir}/annotatedepths/all_samples_indv.depths.tsv.gz"

outdir = "/home/fcalvet/Downloads/to_remove/downsample"

desired_depth = 5000

In [3]:
average_depths_per_sample = pd.read_csv(average_depths_per_sample_file, sep="\t")
average_depths_per_sample.head()

         SAMPLE_ID  avg_depth_sample
0  P19_0001_BDO_01          5080.054
1  P19_0001_BTR_01          5501.250
2  P19_0002_BDO_01          3984.552
3  P19_0002_BTR_01          3874.181
4  P19_0003_BDO_01          5660.784

In [4]:
average_depths_per_sample["correction_factor"] = desired_depth / average_depths_per_sample["avg_depth_sample"]
average_depths_per_sample.loc[average_depths_per_sample["correction_factor"] > 1, "correction_factor"] = 1
average_depths_per_sample

          SAMPLE_ID  avg_depth_sample  correction_factor
0   P19_0001_BDO_01          5080.054           0.984242
1   P19_0001_BTR_01          5501.250           0.908884
2   P19_0002_BDO_01          3984.552           1.000000
3   P19_0002_BTR_01          3874.181           1.000000
4   P19_0003_BDO_01          5660.784           0.883270
..              ...               ...                ...
74  P19_0051_BTR_01          8032.253           0.622490
75  P19_0052_BDO_01          9303.157           0.537452
76  P19_0052_BTR_01          5164.296           0.968186
77  P19_0053_BDO_01          7973.502           0.627077
78  P19_0053_BTR_01          6984.239           0.715898

[79 rows x 3 columns]

In [5]:
all_depths = pd.read_csv(all_depths_file, sep="\t")
all_depths.head()

,CHROM,POS,CONTEXT,P19_0001_BDO_01,P19_0001_BTR_01,P19_0002_BDO_01,P19_0002_BTR_01,P19_0003_BDO_01,P19_0004_BDO_01,P19_0004_BTR_01,...,P19_0047_BTR_01,P19_0048_BTR_01,P19_0050_BDO_01,P19_0050_BTR_01,P19_0051_BDO_01,P19_0051_BTR_01,P19_0052_BDO_01,P19_0052_BTR_01,P19_0053_BDO_01,P19_0053_BTR_01
0,chr1,2529741,GCG,4,1,6,1,0,16,20,...,19,15,14,15,7,39,243,82,8,73
1,chr1,2529742,TCG,4,1,6,1,0,16,20,...,22,15,18,19,7,44,258,86,10,76
2,chr1,2529743,GTC,4,1,6,1,0,16,20,...,22,16,22,19,7,45,269,95,11,78
3,chr1,2529744,ACG,5,1,6,1,1,16,20,...,23,17,23,20,7,48,283,102,12,81
4,chr1,2529745,TCG,5,1,7,1,1,17,21,...,24,17,26,20,7,49,286,106,15,85

In [6]:
all_mutations = pd.read_csv(all_mutations_file, sep="\t")

/tmp/ipykernel_3466629/1237846295.py:1: DtypeWarning: Columns (49,92,112) have mixed types. Specify dtype option on import or set low_memory=False.
  all_mutations = pd.read_csv(all_mutations_file, sep="\t")

In [7]:
all_mutations.head()

,CHROM,POS,REF,ALT,FILTER,INFO,FORMAT,SAMPLE,DEPTH,ALT_DEPTH,...,FILTER.not_searched_COMPLEX,FILTER.MSI12,FILTER.AM_not_searched_SV,FILTER.not_searched_SV,FILTER.SN1.5,FILTER.q22.5,FILTER.v1,FILTER.low_mappability,FILTER.Bias,FILTER.d3
0,chr1,26729450,T,C,low_complex_repetitive;not_in_exons;pSTD,SAMPLE=P19_0024_BTR_01;TYPE=SNV;DP=930;VD=1;AF...,GT:DP:VD:AD:AF:RD:ALD:CDP:CAD:NDP:CDPAM:CADAM:...,"0/1:930:1:929,1:0.0011:929,0:1,0:930:929,1:3:1...",930,1,...,False,False,False,False,False,False,False,False,False,False
1,chr1,26729474,TAG,T,low_complex_repetitive;not_in_exons;pSTD,SAMPLE=P19_0014_BDO_01;TYPE=Deletion;DP=1470;V...,GT:DP:VD:AD:AF:RD:ALD:CDP:CAD:NDP:CDPAM:CADAM:...,"0/1:1470:1:1469,1:0.0007:1469,0:1,0:1470:1469,...",1470,1,...,False,False,False,False,False,False,False,False,False,False
2,chr1,26729479,TTC,T,low_complex_repetitive;not_in_exons;pSTD,SAMPLE=P19_0023_BDO_01;TYPE=Deletion;DP=1984;V...,GT:DP:VD:AD:AF:RD:ALD:CDP:CAD:NDP:CDPAM:CADAM:...,"0/1:1984:1:1983,1:0.0005:1983,0:1,0:1961:1960,...",1961,1,...,False,False,False,False,False,False,False,False,False,False
3,chr1,26729563,G,C,not_in_exons;pSTD,SAMPLE=P19_0023_BDO_01;TYPE=SNV;DP=3490;VD=1;A...,GT:DP:VD:AD:AF:RD:ALD:CDP:CAD:NDP:CDPAM:CADAM:...,"0/1:3490:1:3489,1:0.0003:2657,832:1,0:3490:348...",3490,1,...,False,False,False,False,False,False,False,False,False,False
4,chr1,26729566,TA,T,not_in_exons;p10;pSTD,SAMPLE=P19_0040_BTR_01;TYPE=Deletion;DP=2168;V...,GT:DP:VD:AD:AF:RD:ALD:CDP:CAD:NDP:CDPAM:CADAM:...,"0/1:2168:1:2167,1:0.0005:1845,322:0,1:2114:211...",2114,1,...,False,False,False,False,False,False,False,False,False,False

In [8]:
# Perform uniform sampling with replacement from a pool of 0s and 1s
def uniform_sampling(row):
    ref_depth = row['orig_DEPTH'] - row['ALT_DEPTH']
    pool = [1] * row['ALT_DEPTH'] + [0] * ref_depth
    sampled = np.random.choice(pool, size=row['DEPTH'], replace=False)
    return sampled.sum()

def downsample_mutations(table, proportion, samplename):
    """
    Downsample mutation depths and filter mutations based on VAF.

    FILE format: tab-delimited with columns:
    """

    if not (0 < proportion <= 1):
        print("Error: Proportion must be between 0 and 1.")
        return

    df = table.rename(columns={"DEPTH": "orig_DEPTH"})

    # Downsample the depth values by multiplying and rounding
    df["DEPTH"] = ((df["orig_DEPTH"] * proportion) // 1).astype(int)

    # Use Poisson distribution to decide if mutation remains
    #df['upd_ALT_DEPTH'] = df.apply(lambda row: np.random.poisson(row['VAF'], row['DEPTH']).sum(), axis=1)
    df['ALT_DEPTH'] = df.apply(uniform_sampling, axis=1)
    df['retain_mutation'] = df['ALT_DEPTH'] > 0

    # Filter to retain only mutations
    filtered_df = df[df['retain_mutation']].drop(columns=['retain_mutation', 'orig_DEPTH'])
    filtered_df["VAF"] = df['ALT_DEPTH'] / df["DEPTH"]

    return filtered_df

In [ ]:
# downsample the following samples to 65% I want to keep all the samples in the same final table
samples_to_downsample_df = average_depths_per_sample[average_depths_per_sample["correction_factor"] < 1]
downsampled_mutations = all_mutations[~(all_mutations['SAMPLE_ID'].isin(samples_to_downsample_df["SAMPLE_ID"].tolist()))]
for _, row in samples_to_downsample_df.iterrows():
    sample = row['SAMPLE_ID']

    # Downsample mutations for the current sample
    sample_mutations = all_mutations[all_mutations['SAMPLE_ID'] == sample]
    downsampled = downsample_mutations(sample_mutations, row['correction_factor'], sample)
    downsampled_mutations = pd.concat([downsampled_mutations, downsampled], ignore_index=True)

    # Downsample the depth values by multiplying and rounding
    all_depths[sample] = ((all_depths[sample] * row['correction_factor']) // 1).astype(int)

In [10]:
all_mutations.shape

(64278, 149)

In [11]:
downsampled_mutations.shape

(57301, 149)

In [12]:
downsampled_mutations.to_csv(f"{outdir}/all_samples.downsampled_mutations.tsv", sep="\t", index=False)
all_depths.to_csv(f"{outdir}/all_samples.downsampled_depths.tsv", sep="\t", index=False)

Use the file in assets/useful_scripts to generate the VCF files per sample that will have the mutations information per sample.

```
python deepcsa_maf2samplevcfs.py --mutations-file /home/fcalvet/Downloads/to_remove/downsample/all_samples.downsampled_mutations.tsv --output-dir /home/fcalvet/Downloads/to_remove/downsample/. --maf-from-deepcsa
```

Generate an input.csv file only with the sample and vcf file information, the depths information will be inputted directly with a table of custom_depths.